node {
  stage('Build ng image') {
    def customNodeImage = docker.build("node-with-ng")
    customNodeImage.inside {
      stage('Pull repository') {
        checkout scm
      }
      stage('Install npm') {
        sh 'npm install'
      }
      stage('Build') {
        sh 'ng build --prod'
      }
      stage('Stash dist folder') {
        stash includes: 'dist/**/*', name: 'distFolder'
      }
    }
  }
}
node {
  stage('Unstash dist folder') {
    unstash 'distFolder'
  }
  stage('Build Docker image') {
    def customImage = docker.build("geneiryodan/basic-client:${env.BUILD_ID}", "dockerfiles/nginx")
    stage('Push Docker image'){
      docker.withRegistry('http://registry.hub.docker.com', 'docker-registery'){
            customImage.push()
            customImage.push('latest')
        }
    }
  }
}
